// Open-Meteo weather client (server-side only).
// Open-Meteo is free and requires no API key. Data blend: ICON/ECMWF forecast
// + ERA5-based reanalysis for past days. This is REAL observed/forecast data —
// no synthetic weather is ever generated by this app.

import { FORECAST_DAYS, PAST_DAYS } from "./constants";

export interface WeatherDaily {
  time: string[]; // ISO dates
  tmax: number[]; // °C
  precip: number[]; // mm/day
  et0: number[]; // mm/day (FAO-56 Penman-Monteith, computed by Open-Meteo)
}

export interface WeatherBundle {
  daily: WeatherDaily;
  pastDays: number;
  forecastDays: number;
  fetchedAt: number; // epoch ms
  url: string;
}

const CACHE_TTL_MS = 30 * 60 * 1000; // 30 minutes
const cache = new Map<string, WeatherBundle>();

interface OpenMeteoResponse {
  error?: boolean;
  reason?: string;
  daily?: {
    time: string[];
    temperature_2m_max: (number | null)[];
    precipitation_sum: (number | null)[];
    et0_fao_evapotranspiration: (number | null)[];
  };
}

export class WeatherUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "WeatherUnavailableError";
  }
}

/**
 * Fetch observed (past PAST_DAYS) + forecast (next FORECAST_DAYS) weather for a
 * point. Result cached 30 min in memory.
 */
export async function getWeather(lat: number, lng: number): Promise<WeatherBundle> {
  const key = `${lat.toFixed(3)},${lng.toFixed(3)}`;
  const hit = cache.get(key);
  if (hit && Date.now() - hit.fetchedAt < CACHE_TTL_MS) return hit;

  const params = new URLSearchParams({
    latitude: lat.toFixed(4),
    longitude: lng.toFixed(4),
    daily: "temperature_2m_max,precipitation_sum,et0_fao_evapotranspiration",
    past_days: String(Math.min(PAST_DAYS, 92)),
    forecast_days: String(FORECAST_DAYS),
    timezone: "auto",
  });
  const url = `https://api.open-meteo.com/v1/forecast?${params.toString()}`;

  let res: Response;
  try {
    res = await fetch(url, {
      signal: AbortSignal.timeout(15000),
      headers: { "User-Agent": "agriimpact/1.0 (open-data client)" },
    });
  } catch (e) {
    if (hit) return hit; // serve stale rather than fail
    throw new WeatherUnavailableError(
      `Weather service unreachable: ${e instanceof Error ? e.message : "network error"}`
    );
  }

  if (!res.ok) {
    if (hit) return hit;
    throw new WeatherUnavailableError(`Weather service HTTP ${res.status}`);
  }

  const json = (await res.json()) as OpenMeteoResponse;
  if (json.error || !json.daily || !json.daily.time?.length) {
    throw new WeatherUnavailableError(json.reason ?? "Weather service returned no daily data");
  }

  const d = json.daily;
  const safe = (v: number | null | undefined) => (typeof v === "number" && Number.isFinite(v) ? v : 0);

  const bundle: WeatherBundle = {
    daily: {
      time: d.time,
      tmax: d.temperature_2m_max.map(safe),
      precip: d.precipitation_sum.map(safe),
      et0: d.et0_fao_evapotranspiration.map(safe),
    },
    pastDays: Math.min(PAST_DAYS, d.time.length - FORECAST_DAYS),
    forecastDays: FORECAST_DAYS,
    fetchedAt: Date.now(),
    url: "api.open-meteo.com/v1/forecast (daily: tmax, precip, et0_fao; timezone auto)",
  };
  cache.set(key, bundle);
  return bundle;
}

/** Split the bundle into past observed and forecast segments (by index). */
export function splitPastForecast(w: WeatherBundle): { pastIdx: number[]; forecastIdx: number[] } {
  const total = w.daily.time.length;
  const forecastStart = Math.max(0, total - w.forecastDays);
  const pastIdx: number[] = [];
  for (let i = 0; i < forecastStart; i++) pastIdx.push(i);
  const forecastIdx: number[] = [];
  for (let i = forecastStart; i < total; i++) forecastIdx.push(i);
  return { pastIdx, forecastIdx };
}
